# Generated by Django 5.1.5 on 2025-02-03 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machong', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
